apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
commonLabels:
  stag: production
images:
  - name: me
    newName: gcr.io/me
    newTag: latest
replicas:
  - count: 1
    name: code-server-deployment
patchesStrategicMerge:
  - ./ingress-patch.yaml
