apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: code-server
resources:
  - service.yaml
  - deployment.yaml
  - namespace.yaml
  - ingress.yaml
  - managed-certificate.yaml
  - pvc.yaml
